apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-shop        # lowercase only
  namespace: secureapp
  labels:
    app: secure-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-shop
  template:
    metadata:
      labels:
        app: secure-shop
    spec:
      containers:
        - name: secure-shop
          image: "$IMAGE_REPO:$IMAGE_NAME"
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
      imagePullSecrets:
        - name: ecr-secret-registry-key
