apiVersion: v1
kind: Service
metadata:
  name: "${APP_NAME}"       # quote the variable
  namespace: secureapp
spec:
  selector:
    app: "${APP_NAME}"      # quote the variable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
  type: LoadBalancer
